apiVersion: apps/v1
kind: Deployment
metadata:
  name: terminal-server-deployment
  labels:
    app: terminal-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: terminal-server
  template:
    metadata:
      annotations: 
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9095'
      labels:
        app: terminal-server
    spec:
      containers:
      - name: server
        image: ghcr.io/USERNAME/server-img:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: dockerconfigjson-github-com

