apiVersion: v1
kind: Service
metadata:
  name: terminal-client-service
spec:
  type: NodePort
  selector:
    app: terminal-client
  ports:
  - name: client
    port: 1234
    targetPort: 1234
    nodePort: 30000