apiVersion: v1
kind: Service
metadata:
  name: terminal-server-service
spec:
  type: NodePort
  selector:
    app: terminal-server
  ports:
  - name: server
    port: 3000
    targetPort: 3000
    nodePort: 30001