name: Run Docker Containers and Test Curling Server and Client endpoints
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1 #checkouts your repo, so this workflow can access it
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker Containers
      run: |
        docker build -t server-img -f ./server/Dockerfile ./server
        docker build -t client-img -f ./client/Dockerfile ./client
    - name: Run Docker Containers
      run: |
        docker run -d -p 3000:3000 --name server server-img tail -f /dev/null
        docker run -d -p 1234:1234 --name client client-img tail -f /dev/null
    - name: Determine Container ID
      run: |
        SERVER_ID=$(docker ps -qf "name=server")
        echo "SERVER_ID=$SERVER_ID" >> $GITHUB_ENV
        CLIENT_ID=$(docker ps -qf "name=client")
        echo "CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
    - name: Run npm start
      run: |
        docker exec server sh -c "npm start &"
        docker exec client sh -c "npm start &"
    - name: Test curl command
      run: |
        docker exec $SERVER_ID curl localhost:3000
        docker exec $CLIENT_ID sh -c "apk --no-cache add curl && curl localhost:1234"
      
