name: Run Docker Containers and Test Curling Server and Client endpoints
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1 #checkouts your repo, so this workflow can access it
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker Containers
      run: |
        docker build -t server-img -f ./server/Dockerfile ./server
        docker build -t client-img -f ./client/Dockerfile ./client
    - name: Run Server Container
      uses: addnab/docker-run-action@v3
      with:
          image: server-img
          options: -p 3000:3000
          run: |
            npm start
            curl 127.0.0.1:3000
    - name: Run Client Container
      uses: addnab/docker-run-action@v3
      with:
          image: client-img
          options: -p 1234:1234
          run: |
            npm start
            curl 127.0.0.1:1234
    # - name: Determine Container ID
    #   run: |
    #     SERVER_ID=$(docker ps -qf "name=server")
    #     echo "SERVER_ID=$SERVER_ID" >> $GITHUB_ENV
    #     CLIENT_ID=$(docker ps -qf "name=client")
    #     echo "CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
    # - name: Test curl command
    #   run: |
    #     docker exec $SERVER_ID curl 127.0.0.1:3000
    #     docker exec $CLIENT_ID curl 127.0.0.1:3000
      
