name: Run Docker Containers and Test Curling Server and Client endpoints
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1 #checkouts your repo, so this workflow can access it
    - name: Build and Run Docker Containers
      run: |
        docker build -t server-img -f ./server/Dockerfile ./server
        docker run -d -p 3000:3000 -v $(pwd):/usr/src/app --name server server_img tail -f /dev/null
        docker build -t client-img -f ./client/Dockerfile ./client
        docker run -d -p 1234:1234 -v $(pwd):/usr/src/app --name client client_img tail -f /dev/null
    - name: Test curl command
      run: |
        curl http://localhost:3000
        curl http://localhost:1234
      
