name: Run Docker Containers and Test Curling Server and Client endpoints
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1 #checkouts your repo, so this workflow can access it
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker Containers
      run: |
        docker build -t server-img -f ./server/Dockerfile ./server
        docker build -t client-img -f ./client/Dockerfile ./client
    - name: Run Docker Containers
      run: |
        docker run -d -p 3000:3000 --network host --name server server-img tail -f /dev/null
        docker run -d -p 1234:1234 --network host --name client client-img tail -f /dev/null
    - name: Test curl command
      run: |
        curl http://localhost:3000
        curl http://localhost:1234
      
