name: Test Microk8s curling Server and Client endpoints
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to install MicroK8s
    steps:
    - uses: balchua/microk8s-actions@v0.3.2
      with:
        channel: '1.26/stable'
        addons: '["dns", "dashboard", "istio", "registry"]'
    - name: Test MicroK8s
      id: myactions
      run: |
        cd Kubernetes
        kubectl apply -f deployment_client.yaml
        kubectl apply -f deployment_server.yaml
        kubectl apply -f service_client.yaml
        kubectl apply -f service_server.yaml
    - name: Get Node IP
      id: get_node_ip
      run: echo "NODE_IP=$(microk8s kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')" >> $GITHUB_ENV
    - name: Test curl command
      run: |
        curl http://${{ env.NODE_IP }}:30000
        curl http://${{ env.NODE_IP }}:30001
      
